### ISSUE TITLE
push数据到数组后渲染速度慢

### ISSUE THREAD

**Issue by xualen** [MrSoya/impex#5]
var vm = impex.render(document.body,{
		state:{
			arr:[]
		}
	})
	
$(document).on('click',function(){
	for(var i=10000;i--;){
	vm.state.arr[i] = Math.random().toFixed(2);
        }
})

**Comment by MrSoya** [comment]
尽量不要频繁改动state.xxx，这样会导致性能下降。可以一次性赋值
